--- 
clone: 
  depth: 1
kind: pipeline
name: Yukina-Pipeline
steps: 
  - name: Kernel Pipeline
    image: panchajanya1999/archlinux:latest
    commands:
      - echo "LC_ALL=en_US.UTF-8" | sudo tee -a /etc/environment
      - echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
      - echo "LANG=en_US.UTF-8" | sudo tee -a /etc/locale.conf
      - sudo locale-gen en_US.UTF-8
      - "bash kernel-build.sh"
    environment: 
      TG_TOKEN: 
        from_secret: TG_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID

trigger:
  event:
  - custom
